name: Frontend - Continuous integration

on: [pull_request]

permissions:
  checks: write
  contents: read
  pull-requests: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref_name }} -- ${{ github.event_name }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./app
        run: npx playwright install --with-deps

      - name: Build project
        working-directory: ./app
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Run linter
        working-directory: ./app
        run: npm run lint

      - name: Run tests
        working-directory: ./app
        run: npm test
