name: Continuous integration

on: [pull_request]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref_name }} -- ${{ github.event_name }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload project files
        uses: actions/upload-artifact@v4
        with:
          name: project-files
          path: .

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: project-files
          path: .

      - name: Run linter
        run: npm lint

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: project-files
          path: .

      - name: Run tests
        run: npm test
