name: Deploy

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./app
        run: npx playwright install --with-deps

      - name: Build project
        working-directory: ./app
        run: npm run build

      - name: Run linter
        working-directory: ./app
        run: npm run lint

      - name: Run tests
        working-directory: ./app
        run: npm test

      - name: Copy index to 404
        run: cp ./app/dist/index.html ./app/dist/404.html

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./app/dist

  deploy:
    name: Deploy
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
