name: Functions - Continuous integration

on: [pull_request]

permissions:
  checks: write
  contents: read
  pull-requests: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref_name }} -- ${{ github.event_name }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm-function'

      - name: Install dependencies
        working-directory: ./api/functions
        run: npm ci

      - name: Build project
        working-directory: ./api/functions
        run: npm run build

      - name: Run linter
        working-directory: ./api/functions
        run: npm run lint
